<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoDemoSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'codigo_barras' => '7701234567891',
                'codigo_interno' => 'PAR-001',
                'nombre_comercial' => 'Tempra Forte',
                'nombre_generico' => 'Paracetamol 500mg',
                'principio_activo' => 'Paracetamol',
                'concentracion' => '500 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Bristol-Myers Squibb',
                'registro_sanitario' => 'NN-12345/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 1.50,
                'precio_venta_blister' => 12.00,
                'precio_venta_caja' => 100.00,
                'costo_compra_unidad' => 0.75,
                'stock_unidades' => 500,
                'stock_blisters' => 50,
                'stock_cajas' => 25,
                'stock_minimo_alertas' => 50,
                'estante' => 'A-01',
                'seccion' => 'Analgésicos',
                'ubicacion_detalle' => 'Estante A, fila 1',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567892',
                'codigo_interno' => 'IBU-001',
                'nombre_comercial' => 'Advil',
                'nombre_generico' => 'Ibuprofeno 400mg',
                'principio_activo' => 'Ibuprofeno',
                'concentracion' => '400 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Pfizer',
                'registro_sanitario' => 'NN-12346/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 2.00,
                'precio_venta_blister' => 18.00,
                'precio_venta_caja' => 150.00,
                'costo_compra_unidad' => 1.00,
                'stock_unidades' => 300,
                'stock_blisters' => 30,
                'stock_cajas' => 15,
                'stock_minimo_alertas' => 30,
                'estante' => 'A-02',
                'seccion' => 'Antiinflamatorios',
                'ubicacion_detalle' => 'Estante A, fila 2',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567893',
                'codigo_interno' => 'AMO-001',
                'nombre_comercial' => 'Amoxal',
                'nombre_generico' => 'Amoxicilina 500mg',
                'principio_activo' => 'Amoxicilina',
                'concentracion' => '500 mg',
                'forma_farmaceutica' => 'capsula',
                'laboratorio' => 'Laboratorios Bagó',
                'registro_sanitario' => 'NN-12347/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 8,
                'blisters_por_caja' => 12,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 3.50,
                'precio_venta_blister' => 25.00,
                'precio_venta_caja' => 280.00,
                'costo_compra_unidad' => 1.75,
                'stock_unidades' => 400,
                'stock_blisters' => 40,
                'stock_cajas' => 20,
                'stock_minimo_alertas' => 40,
                'estante' => 'B-01',
                'seccion' => 'Antibióticos',
                'ubicacion_detalle' => 'Estante B, fila 1',
                'controlado' => true,
                'tipo_controlado' => 'receta_simple',
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567894',
                'codigo_interno' => 'LOR-001',
                'nombre_comercial' => 'Loratadina MK',
                'nombre_generico' => 'Loratadina 10mg',
                'principio_activo' => 'Loratadina',
                'concentracion' => '10 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Merck',
                'registro_sanitario' => 'NN-12348/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 1.80,
                'precio_venta_blister' => 15.00,
                'precio_venta_caja' => 130.00,
                'costo_compra_unidad' => 0.90,
                'stock_unidades' => 250,
                'stock_blisters' => 25,
                'stock_cajas' => 12,
                'stock_minimo_alertas' => 25,
                'estante' => 'A-03',
                'seccion' => 'Antihistamínicos',
                'ubicacion_detalle' => 'Estante A, fila 3',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567895',
                'codigo_interno' => 'OME-001',
                'nombre_comercial' => 'Omeprazol MK',
                'nombre_generico' => 'Omeprazol 20mg',
                'principio_activo' => 'Omeprazol',
                'concentracion' => '20 mg',
                'forma_farmaceutica' => 'capsula',
                'laboratorio' => 'Merck',
                'registro_sanitario' => 'NN-12349/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 7,
                'blisters_por_caja' => 14,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 2.50,
                'precio_venta_blister' => 14.00,
                'precio_venta_caja' => 170.00,
                'costo_compra_unidad' => 1.25,
                'stock_unidades' => 350,
                'stock_blisters' => 35,
                'stock_cajas' => 18,
                'stock_minimo_alertas' => 30,
                'estante' => 'C-01',
                'seccion' => 'Gastroprotectores',
                'ubicacion_detalle' => 'Estante C, fila 1',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567896',
                'codigo_interno' => 'DIC-001',
                'nombre_comercial' => 'Voltaren',
                'nombre_generico' => 'Diclofenaco 50mg',
                'principio_activo' => 'Diclofenaco Sódico',
                'concentracion' => '50 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Novartis',
                'registro_sanitario' => 'NN-12350/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 1.20,
                'precio_venta_blister' => 10.00,
                'precio_venta_caja' => 90.00,
                'costo_compra_unidad' => 0.60,
                'stock_unidades' => 200,
                'stock_blisters' => 20,
                'stock_cajas' => 10,
                'stock_minimo_alertas' => 20,
                'estante' => 'A-02',
                'seccion' => 'Antiinflamatorios',
                'ubicacion_detalle' => 'Estante A, fila 2',
                'controlado' => true,
                'tipo_controlado' => 'receta_simple',
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567897',
                'codigo_interno' => 'JAR-001',
                'nombre_comercial' => 'Tosera',
                'nombre_generico' => 'Dextrometorfano 15mg/5ml',
                'principio_activo' => 'Dextrometorfano',
                'concentracion' => '15 mg/5 ml',
                'forma_farmaceutica' => 'jarabe',
                'laboratorio' => 'Laboratorios INTI',
                'registro_sanitario' => 'NN-12351/2024',
                'presentacion_entrada' => 'frasco',
                'unidades_por_blister' => null,
                'blisters_por_caja' => null,
                'fraccionamiento_habilitado' => false,
                'precio_venta_unidad' => 25.00,
                'precio_venta_blister' => null,
                'precio_venta_caja' => null,
                'costo_compra_unidad' => 14.00,
                'stock_unidades' => 60,
                'stock_blisters' => 0,
                'stock_cajas' => 0,
                'stock_minimo_alertas' => 10,
                'estante' => 'D-01',
                'seccion' => 'Jarabes',
                'ubicacion_detalle' => 'Estante D, fila 1',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567898',
                'codigo_interno' => 'CRE-001',
                'nombre_comercial' => 'Clotrimazol Crema',
                'nombre_generico' => 'Clotrimazol 1%',
                'principio_activo' => 'Clotrimazol',
                'concentracion' => '1%',
                'forma_farmaceutica' => 'crema',
                'laboratorio' => 'Bayer',
                'registro_sanitario' => 'NN-12352/2024',
                'presentacion_entrada' => 'tubo',
                'unidades_por_blister' => null,
                'blisters_por_caja' => null,
                'fraccionamiento_habilitado' => false,
                'precio_venta_unidad' => 32.00,
                'precio_venta_blister' => null,
                'precio_venta_caja' => null,
                'costo_compra_unidad' => 18.00,
                'stock_unidades' => 40,
                'stock_blisters' => 0,
                'stock_cajas' => 0,
                'stock_minimo_alertas' => 8,
                'estante' => 'E-01',
                'seccion' => 'Dermatológicos',
                'ubicacion_detalle' => 'Estante E, fila 1',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567899',
                'codigo_interno' => 'INS-001',
                'nombre_comercial' => 'NovoRapid FlexPen',
                'nombre_generico' => 'Insulina Aspártica 100 U/ml',
                'principio_activo' => 'Insulina Aspártica',
                'concentracion' => '100 U/ml',
                'forma_farmaceutica' => 'inyeccion',
                'laboratorio' => 'Novo Nordisk',
                'registro_sanitario' => 'NN-12353/2024',
                'presentacion_entrada' => 'unidad',
                'unidades_por_blister' => null,
                'blisters_por_caja' => null,
                'fraccionamiento_habilitado' => false,
                'precio_venta_unidad' => 180.00,
                'precio_venta_blister' => null,
                'precio_venta_caja' => null,
                'costo_compra_unidad' => 110.00,
                'stock_unidades' => 20,
                'stock_blisters' => 0,
                'stock_cajas' => 0,
                'stock_minimo_alertas' => 5,
                'estante' => 'F-01',
                'seccion' => 'Insulinas',
                'ubicacion_detalle' => 'Estante F, refrigerado',
                'controlado' => true,
                'tipo_controlado' => 'receta_retenida',
                'refrigerado' => true,
            ],
            [
                'codigo_barras' => '7701234567800',
                'codigo_interno' => 'AZI-001',
                'nombre_comercial' => 'Azitromicina MK',
                'nombre_generico' => 'Azitromicina 500mg',
                'principio_activo' => 'Azitromicina',
                'concentracion' => '500 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Merck',
                'registro_sanitario' => 'NN-12354/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 3,
                'blisters_por_caja' => 2,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 12.00,
                'precio_venta_blister' => 32.00,
                'precio_venta_caja' => 60.00,
                'costo_compra_unidad' => 6.50,
                'stock_unidades' => 150,
                'stock_blisters' => 40,
                'stock_cajas' => 30,
                'stock_minimo_alertas' => 15,
                'estante' => 'B-02',
                'seccion' => 'Antibióticos',
                'ubicacion_detalle' => 'Estante B, fila 2',
                'controlado' => true,
                'tipo_controlado' => 'receta_simple',
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567801',
                'codigo_interno' => 'VIT-001',
                'nombre_comercial' => 'Redoxón',
                'nombre_generico' => 'Vitamina C 1000mg',
                'principio_activo' => 'Ácido Ascórbico',
                'concentracion' => '1000 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Bayer',
                'registro_sanitario' => 'NN-12355/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 3.00,
                'precio_venta_blister' => 25.00,
                'precio_venta_caja' => 220.00,
                'costo_compra_unidad' => 1.50,
                'stock_unidades' => 600,
                'stock_blisters' => 60,
                'stock_cajas' => 30,
                'stock_minimo_alertas' => 50,
                'estante' => 'G-01',
                'seccion' => 'Vitaminas',
                'ubicacion_detalle' => 'Estante G, fila 1',
                'controlado' => false,
                'tipo_controlado' => null,
                'refrigerado' => false,
            ],
            [
                'codigo_barras' => '7701234567802',
                'codigo_interno' => 'DIA-001',
                'nombre_comercial' => 'Glucophage',
                'nombre_generico' => 'Metformina 850mg',
                'principio_activo' => 'Clorhidrato de Metformina',
                'concentracion' => '850 mg',
                'forma_farmaceutica' => 'tableta',
                'laboratorio' => 'Merck',
                'registro_sanitario' => 'NN-12356/2024',
                'presentacion_entrada' => 'caja',
                'unidades_por_blister' => 10,
                'blisters_por_caja' => 10,
                'fraccionamiento_habilitado' => true,
                'precio_venta_unidad' => 1.80,
                'precio_venta_blister' => 15.00,
                'precio_venta_caja' => 130.00,
                'costo_compra_unidad' => 0.90,
                'stock_unidades' => 400,
                'stock_blisters' => 40,
                'stock_cajas' => 20,
                'stock_minimo_alertas' => 40,
                'estante' => 'H-01',
                'seccion' => 'Antidiabéticos',
                'ubicacion_detalle' => 'Estante H, fila 1',
                'controlado' => true,
                'tipo_controlado' => 'receta_simple',
                'refrigerado' => false,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
